### ISSUE TITLE
Agregar posibilidad de renombrar variables en el destructuring

### ISSUE THREAD

**Issue by marcorichetta** [undefinedschool/es6-destructuring-notes#1]
Algo que me solucionó un dolor de cabeza fue saber que podía renombrar las variables que desestructuraba.

```js
> const user = {
... fullName: 'Sam Fisher',
... age: 62,
... job: 'spy'
... }

> let { fullName } = user

> fullName
'Sam Fisher'

// Aca le asigno otro nombre a la variable fullName
> let { fullName: nombreCompleto } = user

> nombreCompleto
'Sam Fisher'
```

Más info: https://tylermcginnis.com/object-array-destructuring/

**Comment by nhsz** [comment]
@marcorichetta estaba mencionado brevemente [acá](https://github.com/undefinedschool/notes-es6-destructuring-notes#renombrar-valores-extra%C3%ADdos-aka-alias-custom-names), ahí agregué tus ejemplos, gracias! :+1:

**Comment by marcorichetta** [comment]
La verdad se me pasó ese ejemplo.

> Los nombres que usemos para los parámetros deben coincidir con nombres de propiedades del objeto que se recibe, sino van a tener undefined como valor

Cuando aprendí esto, pensé que no se podría cambiar el nombre de las propiedades y cuando descubrí que podía cambiarse me resultó muy útil, por eso quise agregar ese ejemplo en particular.

Igualmente creo sirve para reforzar el concepto. Gracias a vos! :+1:

**Comment by DanielNdong** [comment]
Recientemente una compañera me presentó ese caso y bueno supe que hacer basicamente gracias a un video que ví en youtube. Esta muy chulo poder hacer eso.
